### ISSUE TITLE
All nodes are tainted master

### ISSUE THREAD

**Issue by kartoch** [ovh/terraform-ovh-publiccloud-k8s#22]
Hello,

I've just deploy a public kubernetes with 3 nodes but I cannot deploy `helm` on it.  The problem seems to be that every node is marked as master and are tainted `node-role.kubernetes.io/master:NoSchedule`.

I forgot `master_as_worker` option in module k8s, so i've to untainted them manually:
```
kubectl taint nodes --all node-role.kubernetes.io/master-
```

But that means if `master_as_worker` is false, every node is tainted as `node-role.kubernetes.io/master:NoSchedule`.

**Comment by yanndegat** [comment]
hi @kartoch 
thats correct and it should stay this way.

we havent released this module (with a tag ) for this issue because we shall provide 
an example of how to add nodes to an existing cluster. 
its a WIP and should be released soon

we'll reference this issue when submitting so that you'll be informed

**Comment by kartoch** [comment]
Another points directly related to the discussion: all nodes are masters.
```
NAME      STATUS    ROLES     AGE       VERSION
k8s-0     Ready     master    1m        v1.9.2
k8s-1     Ready     master    54s       v1.9.2
k8s-2     Ready     master    1m        v1.9.2
k8s-3     Ready     master    2m        v1.9.2
k8s-4     Ready     master    16s       v1.9.2
```

**Comment by yanndegat** [comment]
relates to #6

**Comment by kartoch** [comment]
I understand you will work on masters/workers later. I close this issue to let #6 to be the main one about this.
