### ISSUE TITLE
Taint master is not apply during k8s-init

### ISSUE THREAD

**Issue by kartoch** [ovh/terraform-ovh-publiccloud-k8s#38]
Based on commit 1e087e92fba42a90bede1f1111c0d1b391976192, it seems taint is not applied to master nodes to authorize them to be worker. More specifically the following code in `k8s-init` seems to have no effect:
```
# Untaint node if needed
if [ "$$MASTER_AS_WORKER" == 1 ]; then
   /opt/k8s/bin/kubectl --kubeconfig=/etc/kubernetes/admin.conf taint nodes --all node-role.kubernetes.io/master-
fi
```
I've to apply it manually after cluster setup:
```
kubectl taint nodes --all node-role.kubernetes.io/master-
```
EDIT: my configuration is kartoch/terraform-ovh-publiccloud-k8s@7837962d619dce3289e466bdfbe1ea86892370c6

**Comment by kartoch** [comment]
I can confirm this bug is still present on the latest commit:
```
apiVersion: v1
items:
- apiVersion: v1
  kind: Node
  metadata:
    annotations:
      flannel.alpha.coreos.com/backend-data: '{"VtepMAC":"3a:29:4a:f0:96:8c"}'
      flannel.alpha.coreos.com/backend-type: vxlan
      flannel.alpha.coreos.com/kube-subnet-manager: "true"
      flannel.alpha.coreos.com/public-ip: 54.38.91.107
      node.alpha.kubernetes.io/ttl: "0"
      volumes.kubernetes.io/controller-managed-attach-detach: "true"
    creationTimestamp: 2018-03-04T17:24:41Z
    labels:
      beta.kubernetes.io/arch: amd64
      beta.kubernetes.io/os: linux
      kubernetes.io/hostname: myk8s-0
      node-role.kubernetes.io/master: ""
    name: myk8s-0
    namespace: ""
    resourceVersion: "784"
    selfLink: /api/v1/nodes/myk8s-0
    uid: ec2bb1bb-1fd0-11e8-b736-fa163e8268fe
  spec:
    externalID: myk8s-0
    podCIDR: 10.2.0.0/24
    taints:
    - effect: NoSchedule
      key: node-role.kubernetes.io/master
```

**Comment by Devatoria** [comment]
Hi,

Thank you for the issue, I will take a look at it as soon as possible. I'll check if the untaint is either not done at all or done too soon, maybe due to a race condition.

**Comment by Devatoria** [comment]
Looks like a mix between a race condition and a bad condition in the init script. Please note that untainting an already untainted node makes the script fail. Now, we untaint only the current node (if needed), since each node initializes itself.
