### ISSUE TITLE
"Careful this keypair should not be using passphrase!"

### ISSUE THREAD

**Issue by yanndegat** [ovh/terraform-ovh-publiccloud-k8s#59]
why? 
@pierre-peronnet-ovh

**Comment by kartoch** [comment]
SSH private key has been removed from module requirements, so it is managed outside the project. The user must preload the private key with ssh-agent before. This is the present approach and is the best solution for me.

**Comment by kartoch** [comment]
No passphrase is interesting only if keypair are copied to remote node. Maybe for private cluster ?

**Comment by yanndegat** [comment]
this issue is not relevant.
passphrase on keypair shall be authorized
closing
