### ISSUE TITLE
I cannot boostrap node only instances

### ISSUE THREAD

**Issue by bewiwi** [ovh/terraform-ovh-publiccloud-k8s#6]
I can't create infra with 3 masters and 5 workers.

**Comment by Devatoria** [comment]
Some things to take in consideration:
- nodes must not host etcd
- nodes must not host cfssl
- nodes must not pre-pull useless images such as those from the k8s control plane (only CNI and proxy should be needed actually)
- nodes must get a bootstrap token from etcd
- nodes must join the cluster using kubeadm CLI

**Comment by kartoch** [comment]
For flexibility, each nodes are defined by the following attributes:

* openstack name
* openstack flavor (nodes are not necessary identical)
* other openstack attributes, like attached disk for storage
* node name
* node label(s): node have large storage, node has a GPU, etc.
* role (master or worker)

Futhermore, etcd members are not necessary on the same instance as kubernetes masters (see [Operating etcd clustersfor kubernetes](https://kubernetes.io/docs/tasks/administer-cluster/configure-upgrade-etcd/))

*

**Comment by yanndegat** [comment]
+1
