### ISSUE TITLE
support for -centos/cl- multiple OSes adds too much complexity

### ISSUE THREAD

**Issue by yanndegat** [ovh/terraform-ovh-publiccloud-k8s#62]
by supporting at least 2 OSes, 
it adds complexity on the installation part.
and it also adds complexity on the userdata part 

coreos deprecated a "cloudinit" compatible support for userdata in favor of its ignition format
other oses still relies on cloudinit format

coreos container linux long term support by redhat is unclear.
we shouldnt spend too much effort on this by now

and refocus on widely adopted distros such as debian & fedora families

a good target in the end could be fedora atomic

**Comment by yanndegat** [comment]
and no immediate value

**Comment by kartoch** [comment]
One of the added values of  centos / redhat / [atomic](https://www.projectatomic.io/) is the excellent SeLinux support. At the present time [coreos supports SeLinux](https://coreos.com/os/docs/latest/selinux.html) but is is disabled by default and has limitations:

> SELinux enforcement is currently incompatible with Btrfs volumes and volumes that are shared between multiple containers.

IMHO switching to atomic (best choice for containers in redhat world) really depends of the SeLinux integration (or not).

**Comment by yanndegat** [comment]
hi @kartoch

now that redhat acquired coreos to develop its kubernetes/containers support

i don't know what is the "atomic" future within the redhat catalog

did they communicate on this subject?

**Comment by yanndegat** [comment]
extract of their FAQ on this subject:
https://www.redhat.com/en/blog/faq-red-hat-acquire-coreos

Whereas, some of the delivery mechanisms pioneered by Container Linux will be reviewed by a joint integration team and reconciled with Atomic.

**Comment by yanndegat** [comment]
here's redhat comments on this subject

https://groups.google.com/forum/#!topic/coreos-user/GR4YlF2c1dM

here's a proposal for ignition support in fedora atomic
https://pagure.io/atomic-wg/issue/450

**Comment by yanndegat** [comment]
by now maybe we should support only one cloudinit format as long as possible
