### ISSUE TITLE
Provide compute instances to modules

### ISSUE THREAD

**Issue by kartoch** [ovh/terraform-ovh-publiccloud-k8s#64]
Following my remarks in #6, there is at least three reasons to provide compute instances to the k8s module instead of letting this module generate the instance:

- Non-heterogeneous worker nodes with different flavors
- Instances are provided with additional fields like metadata (but this also can be done after provisioning)
- OVH instances are half-price with monthly engagement. For long-running cluster the user can log into the OVH interface, create the instances then use the ID number to ask for reinstall. 

For the last point it can be tricky: 

- user must be sure to not destroy instance during terraform un-provisioning
- user must create the instances with the correct image create with packer (maybe it is possible to avoid this and just request install with another image while keeping the instance)

**Comment by yanndegat** [comment]
hi @kartoch 

thanks for the feedback



    Non-heterogeneous worker nodes with different flavors
> actually i think you can already achieve this. see example with workers.
you could typically duplicate a workers module & set it another count+flavor

    Instances are provided with additional fields like metadata (but this also can be done after provisioning)
> could you be more specific? 


    OVH instances are half-price with monthly engagement. For long-running cluster the user can log into the OVH interface, create the instances then use the ID number to ask for reinstall.
> you can activate monthly billing on a running instance without having to destroy it through an OVH API call. We're also thinking of making this available through the openstack api but it's still in design phase.

**Comment by kartoch** [comment]
> actually i think you can already achieve this. see example with workers. you could typically duplicate 
> a workers module & set it another count+flavor

OK, good.

> you can activate monthly billing on a running instance without having to destroy it through an OVH 
> API call. We're also thinking of making this available through the openstack api but it's still in design 
> phase.

Great, it is what i am looking for.

>> Instances are provided with additional fields like metadata (but this also can be done after 
>> provisioning)
> could you be more specific?

Add metadata to instances managed by terraform after provisioning: https://www.terraform.io/docs/providers/openstack/r/compute_instance_v2.html .

It would also be great to have a default mechanism to add label to nodes, for instance the key:
```
ovh.openstack.flavor = "s1-8"
```

**Comment by kartoch** [comment]
First two points solved, last point tracked in #78.
