### ISSUE TITLE
Cannot get logs

### ISSUE THREAD

**Issue by kartoch** [ovh/terraform-ovh-publiccloud-k8s#65]
Based in commit a73065c0e6f5b7d51cbbe4818258f129a7f24839, kubectl cannot get logs.

Using kubectl on the computer which did the provisioning:

- Access the log of the kube-controller-manager of first master (the remote address set in kubectl configuration):

```
$ kubectl logs kube-controller-manager-k8s-master-0 --namespace=kube-system                                                                                             
I0322 11:35:10.271991       1 controllermanager.go:108] Version: v1.9.2
I0322 11:35:10.282449       1 leaderelection.go:174] attempting to acquire leader lease...
E0322 11:35:10.283684       1 leaderelection.go:224] error retrieving resource lock kube-system/kube-controller-manager: Get https://217.182.80.247:6443/api/v1/namespaces/kube-system/endpoints/kube-controller-manager: dial tcp 217.182.80.247:6443: getsockopt: connection refused
```
- Access the log of the kube-controller-manager of other masters:

```
$ kubectl logs kube-controller-manager-k8s-master-1 --namespace=kube-system                                                                                             
Error from server: Get https://217.182.80.229:10250/containerLogs/kube-system/kube-controller-manager-k8s-master-1/kube-controller-manager: dial tcp 217.182.80.229:10250: getsockopt: connection timed out
```
Same when using kubectl on one of the Master nodes

- Access the log of the kube-controller-manager of first master (the remote address set in kubectl configuration):
```
core@k8s-master-0 ~ $ sudo /opt/k8s/bin/kubectl --kubeconfig=/etc/kubernetes/admin.conf logs kube-controller-manager-k8s-master-0 --namespace=kube-system
I0322 11:35:10.271991       1 controllermanager.go:108] Version: v1.9.2
I0322 11:35:10.282449       1 leaderelection.go:174] attempting to acquire leader lease...
E0322 11:35:10.283684       1 leaderelection.go:224] error retrieving resource lock kube-system/kube-controller-manager: Get https://217.182.80.247:6443/api/v1/namespaces/kube-system/endpoints/kube-controller-manager: dial tcp 217.182.80.247:6443: getsockopt: connection refused
```
- Access the log of the kube-controller-manager of other masters:

```
core@k8s-master-0 ~ $ sudo /opt/k8s/bin/kubectl --kubeconfig=/etc/kubernetes/admin.conf logs kube-controller-manager-k8s-master-1 --namespace=kube-system
Error from server: Get https://217.182.80.229:10250/containerLogs/kube-system/kube-controller-manager-k8s-master-1/kube-controller-manager: dial tcp 217.182.80.229:10250: getsockopt: connection timed out
```

**Comment by yanndegat** [comment]
hi @kartoch 
thanks for logging this issue

what example have you ran?

**Comment by kartoch** [comment]
My configuration is available here: kartoch/terraform-ovh-publiccloud-k8s@f2ef59e94e382284ada82efd60becf8233a3cd10

**Comment by kartoch** [comment]
It is working well when:

- accessing the log of a pod of first master node (the remote address set in kubectl configuration)  from the remote computer which did the provisioning (i.e. the kubectl access master node contain the target pod)
- accessing the log of a pod of first master node when using kubectl on the first master node.

It does not work when:

1. accessing the log of a pod in other master nodes from the remote computer which did the provisioning
2. accessing the log of a pod in other master nodes when using kubectl on the first master node.

For one, it is just a security group to add for the provisioning. But I don't understand for master to master access to port 10250 because the rules seems present in openstack security groups.

**Comment by kartoch** [comment]
Found it, communication must be permitted to port 10250 for masters to masters and provisioner to masters.

In `main.tf` of the configuration:

```
resource "openstack_networking_secgroup_rule_v2" "k8s-api" {
  direction         = "ingress"
  ethertype         = "IPv4"
  protocol          = "tcp"
 remote_ip_prefix = "${data.http.myip.body}/32"
  port_range_min    = 10250
  port_range_max    = 10250
  security_group_id = "${module.k8s_secgroups.master_group_id}"
}
```
in `main.tf` of `k8s-secgroups`:

```
resource "openstack_networking_secgroup_rule_v2" "kubelet_master_master" {
  direction         = "ingress"
  ethertype         = "IPv4"
  protocol          = "tcp"
  port_range_min    = 10250
  port_range_max    = 10250
  remote_group_id   = "${openstack_networking_secgroup_v2.master.id}"
  security_group_id = "${openstack_networking_secgroup_v2.master.id}"
}

```
