### ISSUE TITLE
Problem: I can't deploy Loadbalancer

### ISSUE THREAD

**Issue by bewiwi** [ovh/terraform-ovh-publiccloud-k8s#7]
As a user i want to use loadbalancer in front of my service

**Comment by kartoch** [comment]
You mean external loadbalancer ? (inside a kubernetes cluster, it seems to be managed by the services).

**Comment by bewiwi** [comment]
I mean a load balancer like traefik install as a daemonset on an instance and controlled with an ingress-controler.

**Comment by kartoch** [comment]
* Traefik as ingress controller in kubernetes: https://docs.traefik.io/user-guide/kubernetes/
* Available as helm chart: https://github.com/kubernetes/charts/tree/master/stable/traefik

**Comment by kartoch** [comment]
Is issue solved ?
